### ISSUE TITLE
Add Port of Virginia to C-Port

### ISSUE THREAD

**Issue by briannaess** [CEMPD/ctools#100]
The Port of Virginia needs to be added to the drop-down box on C-Port.

**Comment by cseppan** [comment]
I tried using Port of Virginia, VA in the pull down, but that didn't get the right location from Google Maps. (Oddly it works fine if you enter it on the Google Maps site.) For now, I've left the pull down as Norfolk, VA .

**Comment by cseppan** [comment]
I updated the drop-down menu to display "Port of Virginia, VA". The value that gets sent to Google Maps is still "Norfolk, VA".

**Comment by michellegrace** [comment]
I think we pretty-much have this done. We can re-open this issue if needed.
