### ISSUE TITLE
Use different tables for point, area, underway sources in C-Port

### ISSUE THREAD

**Issue by briannaess** [CEMPD/ctools#101]
I created new tables: 
* us_area_sources_merged
* us_pt_sources_merged
* us_underway_sources_merged

These new tables have everything from Region 4 plus the Port of VA values. Note that there may be some potential column name changes. See ie-cport listserv email for more information.

**Comment by cseppan** [comment]
I loaded an updated version of the us_area_sources_merged table from Brian's database into ctools_dev today (Mar. 26).

I ran queries to delete and replace the contents of the web application tables with the new data from the us_*_merged tables and the tiger2010_rail_for_analysis table.

us_area_sources_merged -> area_sources
us_pt_sources_merged -> point_sources
us_underway_sources_merged -> ships_in_transit
tiger2010_rail_for_analysis -> rails
