### ISSUE TITLE
Error running Port of Virginia area sources

### ISSUE THREAD

**Issue by cseppan** [CEMPD/ctools#103]
Here's the output in the web app log.

 Input Directory is: 
 /nas01/depts/ie/cempd/EPA-RARE/ctools/street2/1427408398.07/
 Error reading source file near index            1

The first couple lines of the area.csv file:

name,object_id,sf_id,x,y,nox,benz,pm2_5,dies_pm25,ec,oc,co,form,ald2,acro,butal_3
Port_of_Virginia_-_Norfolk_International_Terminal,63,13737,47014151.5042,3130302.51791,719.96133555,0.30270480481,23.0809854196,-999,17.7954387868,4.0622545444,146.346828998,0.00044769063,0,0.04323164479,-999
Port_of_Virginia_-_Norfolk_International_Terminal,63,13737,47018911.4093,3135842.53498,719.96133555,0.30270480481,23.0809854196,-999,17.7954387868,4.0622545444,146.346828998,0.00044769063,0,0.04323164479,-999

**Comment by cseppan** [comment]
Same error for ship-in-transit sources:

 Input Directory is: 
 /nas01/depts/ie/cempd/EPA-RARE/ctools/street2/1427409019.98/
 Error reading source file near index            1

sit.csv:
gid,startx,starty,endx,endy,sf_id,nox,benz,pm2_5,dies_pm25,ec,oc,co,form,ald2,acro,butal_3,stack_height,stack_
diameter,stack_velocity,stack_temperature
1371,1820829.3501,-139145.9925,1822347.7217,-140146.0916,13737,1.73186365077,0.00124392089512,0.0490979500615,
-999,0.000245531579744,0.00552350495797,0.15969858591,1.80299294862e-06,0,-999,-999,19.99,0.8,4,554.82
1372,1820007.7439,-138604.4923,1820829.3501,-139145.9925,13737,0.937305245499,0.000673224811584,0.026572395647
6,-999,0.000132884616827,0.00298938670394,0.0864307777384,9.7580126911e-07,0,-999,-999,19.99,0.8,4,554.82
1373,1817427.2292,-135471.9909,1816104.8553,-133404.0304,13737,2.31822047841,0.00166507501402,0.0657210359661,
-999,0.000328661171453,0.00739359723873,0.213767713219,2.41343201243e-06,0,-999,-999,19.99,0.8,4,554.82

**Comment by cseppan** [comment]
The read error is due to lines longer than 200 characters. Looks like increasing the length of the "testread" variable in each of the *_read_sources.f90 routines should take care of it. I'd suggest 500 characters for some breathing room.

**Comment by michellegrace** [comment]
I increased this in my working version. This will be fixed when I have a dispersion code update.
