### ISSUE TITLE
No results for Port of Virginia roads

### ISSUE THREAD

**Issue by cseppan** [CEMPD/ctools#105]
No errors on execution, but the results file (results_CPORT_ROAD_Output.csv) has no records, just the header.

 Input Directory is: 
 /nas01/depts/ie/cempd/EPA-RARE/ctools/street2/1427408793.37/
TOTALruntime =     40.574 seconds.

roads.csv:
id,from_x,from_y,to_x,to_y,sf_id,stfips,ctfips,fclass_rev,aadt,mph_am,mph_md,mph_pm,mph_op,gas_car_multiplier,
gas_truck_multiplier,diesel_car_multiplier,diesel_truck_multiplier
17359,1823282.3185,-140976.3193,1823041.8452,-140433.5407,13737,51,710,14,3022,20,20,19,21,1,1,1,1
15009,1834624.7753,-128641.6957,1834871.9938,-123144.1189,13737,51,810,2,10624,43,43,41,44,1,1,1,1
16989,1834989.5292,-130059.664,1834627.478,-129405.5567,13737,51,810,2,10624,43,43,41,44,1,1,1,1
16989,1834627.478,-129405.5567,1834624.7753,-128641.6957,13737,51,810,2,10624,43,43,41,44,1,1,1,1
16993,1835046.2677,-130227.5421,1834989.5292,-130059.664,13737,51,810,2,10624,43,43,41,44,1,1,1,1

**Comment by michellegrace** [comment]
This was fixed when I changed the analytical line source algorithm to match the one in C-LINE. Now this computes for roads.
