### ISSUE TITLE
C-PORT does not use some options

### ISSUE THREAD

**Issue by michellegrace** [CEMPD/ctools#108]
We made a decision way back to not have the options for "hour" or "day". These options are not present in the dispersion code input file, but are shown as options on the web-tool:

![screen shot 2015-03-28 at 7 30 25 am](https://cloud.githubusercontent.com/assets/10077162/6880902/9cf406d6-d51c-11e4-93e7-83809a9be735.png)

This can be changed in the dispersion code pretty quickly, but it was a decision that was made and could confuse the user if these options do not change anything in the results. It was a distinction we wanted to keep between the 2 tools, i.e. "if users want to study traffic they should use C-LINE".

btw... in the dispersion code I hardwired these options to be AMpeak and weekday, respectively.

**Comment by michellegrace** [comment]
This is also the case for the gas/diesel and car/truck multipliers for roadways.

**Comment by michellegrace** [comment]
Based on our discussion on 4/15/15, we decided to make the CPORT_Roads and CLINE executables the same. Therefore, we will have all these options available in the CPORT tool. Let's revisit later, but this issue can probably be closed.

**Comment by cseppan** [comment]
Treehug now runs C-LINE for CPORT road analysis, instead of CPORT_Roads.
