### ISSUE TITLE
What is "lock map data" suppose to do?

### ISSUE THREAD

**Issue by michellegrace** [CEMPD/ctools#113]
It looks like this currently "locks" the sources, so when the user moves around no more sources are loaded. 

However, I believe that the receptors are generated in the user's view window on whatever view they are on, not on the view they had when they locked the map data.

Let's check this!

**Comment by cseppan** [comment]
Correct on both counts.

I added an option labeled "Reset map center and zoom level" that shows up when the map data is locked. Clicking the link will reset the map view to the center and zoom that were set when the map data was locked. This lets you move around the map, zoom in, edit sources, etc. and then return to your starting view.
