### ISSUE TITLE
"X" when you select multiple sources

### ISSUE THREAD

**Issue by michellegrace** [CEMPD/ctools#115]
Brian expressed the desire to have this feature.... From our discussion he had problems when he selected multiple segments and maybe selected something by mistake, it would be nice to have a little "x" button on the source line of the table to be able to get it out of the selected set without having to track it down again. This would be extremely helpful when there are many small segments close to each other, so you dont have to zoom in (changing user view and receptors) and unselect.

**Comment by cseppan** [comment]
The last column in the selected sources tables now shows a red X. Clicking the X will remove the corresponding source from the list of selected sources.
