### ISSUE TITLE
Reset to default values

### ISSUE THREAD

**Issue by michellegrace** [CEMPD/ctools#116]
Brian also expressed the desire to have this feature... where you could have a "reset to default values" .. 

Suppose you had a project where you wanted to look at the effects of increasing or decreasing emissions from a particular source. To do this the user takes the default values and applies a multiplier of "10" and applies... now the emissions are 10x greater. Now to run the scenario when the emissions are decreased the user has to again multiply by 0.1 to return to defaults, then by 0.1 again to get a 1/10th emission scenario.... 

He expressed the desire to have a button that would repopulate the values with the database values. So you could apply a multiplier, run, reset to defaults, apply a multiplier, and run... this would also avoid some rounding errors when the multipliers are applied to numbers with lots of significant digits.

**Comment by joellenb** [comment]
Didn’t we talk about a “reset values” button some months ago? I agree that such a feature would be very useful for the user in other situations, including as an “oops” key.

Would this functionality apply to all sources of a source type (e.g., roads, ships in transit) or to all sources?

Jo Ellen

**Comment by michellegrace** [comment]
Yes and yes. I think you and I discussed something like this before and I think it should be for all source types... this would be especially useful when sources overlap, such as point and area sources, sometimes you click on the area or the point and you just want to clear one or the other and it is hard to click on the one you want.

**Comment by cseppan** [comment]
For sources that have been modified, the source name (facility, railway owner, road, etc.) is now shown in blue. There's a reset button for each modified source which will reset that source's values to the database values. When multiple sources are selected, there's a Reset Sources button next to the Apply Modifiers button that resets all the selected sources.
