### ISSUE TITLE
replicate road receptor generation for railways

### ISSUE THREAD

**Issue by cseppan** [CEMPD/ctools#120]
- use exact same approach

**Comment by cseppan** [comment]
Railways and ship in transit sources now have receptors placed along the lines. The receptors are created the same way as road sources: placed every 200 meters along the line, extending perpendicular at 5 and 25 meters on either side.

**Comment by arunacs** [comment]
Sweet.. I just ran Charleston with all default options, but I am not sure I see an improvement from prior. Michelle, do you have a screenshot from prior tests to compare against?
________________________________

**Comment by michellegrace** [comment]
I do not have one, but you can look through previous issues and see if there is something. I do have the offline runs of Charleston in my code directory, these would have the previous receptor generation.

How many additional receptors are we getting? Is there a noticeable increase in runtime?

-Michelle
------------------------------------------------------------------
Michelle G. Snyder, Environmental Modeler
Institute for the Environment/CEMPD
University of North Carolina at Chapel Hill
Campus Box 1105 (27599-1105)
Europa Center Suite 490  Rm. 4052
100 Europa Dr.
Chapel Hill, NC 27517

phone: 919-843-7561
email: michellesnyder@unc.edu<mailto:michellesnyder@unc.edu>
