### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by kdtalgo** [CEMPD/ctools#126]
Is it possible to add a progress bar after the user hits Submit when running a new scenario?

Perhaps it's just me, but when I ran C-PORT for the first time, staring at the spinning wheel for more than a minute gave me the impression that C-PORT is hanging and not working. Someone not familiar with the process will not be aware of what is going on under the hood. I suspect some people will refresh their browser, or close out their browser, after seeing a spinning wheel for more than a few minutes with no indication of progress.

If a progress bar isn't possible, what about adding a pop-up message that indicates that the scenario is actually running and not hanging?

FYI, my initial test was to run for all sources (default) so I suspect that causes the longer run times.

**Comment by joellenb** [comment]
The spinning wheel is the method by which C-PORT tells the user that it is working. If the process times out, then a message is displayed to the user in the browser window.

Jo Ellen

**Comment by michellegrace** [comment]
I am linking this issue to #92 (adding a STOP button). These are both used to inform the user of the progress of their run, or stop it in mid-run. Both these issues of informing the user need to be addressed in future versions of the tool.

**Comment by cseppan** [comment]
Sept. release will have async handling.
