### ISSUE TITLE
Negative emissions should not be allowed

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#132]
The up/down arrow widgets for modifying the area source emissions can go negative. See attached image -5 highlighted for NOx under 3rd source.

Need to make certain that the only negative emission value allowed is -999 for missing data. If that is not feasible, then prevent the down arrow from entering an emissions value < 0.

![negativeemissions_areasrcs_06012015](https://cloud.githubusercontent.com/assets/10145737/7918559/3ae9e38a-0860-11e5-8cd3-d464b9c855a9.PNG)

NOTE: The same widget for the other source types should have the same behavior (not <0).

**Comment by joellenb** [comment]
Also need to check when modifying multiple sources at a time. The multiplier value for emissions currently allows negative values and performs the multiplication when the values are applied, resulting in negative emissions. However, emissions cannot be negative.

**Comment by cseppan** [comment]
I updated all the numeric fields to use zero as the minimum value. This includes the stack parameters, emissions multipliers, and emissions fields.
