### ISSUE TITLE
Editing more than 1 point source but not together

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#133]
I just ran into a situation that I hadn't noticed in the past. I was manually editing 1 point source on a screen and then flipped around to other point source pages and saw that there was another point source set up as being manually edited.

It appears that when a point source is being edited (such as the 4th one on a page), that same positional point source (in the example, the 4th one on each page) is being edited on all pages. Pressing the Stop Editing button on one page also stops the editing on the other pages.

**Comment by cseppan** [comment]
Switching pages in the source list now resets the editing flag. This is the same as if the user clicked the Stop Editing button.
