### ISSUE TITLE
use consistent download structure between C-LINE and C-PORT

### ISSUE THREAD

**Issue by cseppan** [CEMPD/ctools#134]
Current C-LINE output

single scenario named Raleigh Base
contents of downloadable archive Raleigh_Base_143326064966.tar.gz
___
concentrations.png
receptors.csv
ctools.prj
Raleigh_Base/CTOOLS_Inputs.txt
Raleigh_Base/results_CTOOLS_HOURLY_ROAD_Output.csv
Raleigh_Base/roads.csv

Does the single scenario output need a subdirectory within the package?
For C-PORT, should a consolidated results file be included?

comparison of two scenarios: Raleigh Summer vs. Raleigh Base
contents of downloadable archive Raleigh_Summer_vs_Raleigh_Base_14332638240.tar.gz
___
concentrations.png
receptors.csv
results.csv (concentration differences as tabular data)
ctools.prj
Raleigh_Summer/CTOOLS_Inputs.txt
Raleigh_Summer/results_CTOOLS_HOURLY_ROAD_Output.csv
Raleigh_Summer/roads.csv
Raleigh_Base/CTOOLS_Inputs.txt
Raleigh_Base/results_CTOOLS_HOURLY_ROAD_Output.csv
Raleigh_Base/roads.csv

This structure assumes the receptors are the same between the two scenarios - could they be different? Can just one scenario have user-added sources? In C-PORT runs, can the two scenarios include different types of sources (e.g. one scenario includes roads, the other doesn't)?

**Comment by arunacs** [comment]
Please see my responses below.
For Single scenario, it is probably okay to have a subdir to retain scalability with multiple scenarios and comparisons later.

Yes for consolidated results in C-PORT. 

For the comparison case above:
- The receptors cannot be different for comparisons. 
- We haven't discussed having different C-PORT scenarios having different source types for comparisons. However, coming to think of it, I don't think we need to do that. If we want to compare relative magnitudes from multiple source types, we run one or more sources, and then enable comparisons at a specific receptor for multiple source types. This feature needs to be added though for the next round.

**Comment by cseppan** [comment]
C-PORT now matches C-LINE output.

single scenario named Morehead City Winter
contents of downloadable archive Morehead_City_Winter_143340950285.tar.gz
___
concentrations.png
receptors.csv
ctools.prj
Morehead_City_Winter/CTOOLS_Inputs.txt
Morehead_City_Winter/area.csv
Morehead_City_Winter/points.csv
Morehead_City_Winter/railways.csv
Morehead_City_Winter/roads.csv
Morehead_City_Winter/sit.csv
Morehead_City_Winter/results_CTOOLS_HOURLY_AREA_Output.csv
Morehead_City_Winter/results_CTOOLS_HOURLY_POINT_Output.csv
Morehead_City_Winter/results_CTOOLS_HOURLY_RAIL_Output.csv
Morehead_City_Winter/results_CTOOLS_HOURLY_ROAD_Output.csv
Morehead_City_Winter/results_CTOOLS_HOURLY_SIT_Output.csv
Morehead_City_Winter/results.csv (merged results for all sources)

comparison of two scenarios: Morehead City Summer vs. Morehead City Winter
contents of downloadable archive Morehead_City_Summer_vs_Morehead_City_Winter_143340976477.tar.gz
___
concentrations.png
receptors.csv
results.csv (concentration differences as tabular data)
ctools.prj
Morehead_City_Winter/CTOOLS_Inputs.txt
Morehead_City_Winter/area.csv
Morehead_City_Winter/points.csv
Morehead_City_Winter/railways.csv
Morehead_City_Winter/roads.csv
Morehead_City_Winter/sit.csv
Morehead_City_Winter/results_CTOOLS_HOURLY_AREA_Output.csv
Morehead_City_Winter/results_CTOOLS_HOURLY_POINT_Output.csv
Morehead_City_Winter/results_CTOOLS_HOURLY_RAIL_Output.csv
Morehead_City_Winter/results_CTOOLS_HOURLY_ROAD_Output.csv
Morehead_City_Winter/results_CTOOLS_HOURLY_SIT_Output.csv
Morehead_City_Winter/results.csv (merged results for all sources)
Morehead_City_Summer/CTOOLS_Inputs.txt
Morehead_City_Summer/area.csv
Morehead_City_Summer/points.csv
Morehead_City_Summer/railways.csv
Morehead_City_Summer/roads.csv
Morehead_City_Summer/sit.csv
Morehead_City_Summer/results_CTOOLS_HOURLY_AREA_Output.csv
Morehead_City_Summer/results_CTOOLS_HOURLY_POINT_Output.csv
Morehead_City_Summer/results_CTOOLS_HOURLY_RAIL_Output.csv
Morehead_City_Summer/results_CTOOLS_HOURLY_ROAD_Output.csv
Morehead_City_Summer/results_CTOOLS_HOURLY_SIT_Output.csv
Morehead_City_Summer/results.csv (merged results for all sources)

**Comment by cseppan** [comment]
When selecting scenarios to compare, I added a check that the two scenarios both include the same source types. Previously, you could select scenarios that were different which would cause a backend error if the receptors didn't match. This will come up again once adding sources is complete but I'll close this for now.
