### ISSUE TITLE
Reorganize C-PORT's "Perform analysis" screen

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#136]
This screen needs to be reorganized from v1.0 and additional help widgets need to be added per the following mockup:

![c-port_v1_1_performanalysiswindow_06032015](https://cloud.githubusercontent.com/assets/10145737/7966580/02dfd0dc-09f3-11e5-9493-2952b685f12d.png)

**Comment by cseppan** [comment]
I've reordered the form elements and added the help pop-up links. Additionally, I've merged the help text changes from the new_source_JEB branch.

**Comment by michellegrace** [comment]
Catherine,
This looks great!
Can you also rearrange the C-LINE perform analysis window? This should look identical, but without the "select you source type" section, and if you take that our I think the "select you emission parameters..." section needs to be -1 indented so it lines up with the "select your met. conditions" section.

THANKS!!

**Comment by cseppan** [comment]
I've rearranged the C-LINE analysis menu to match C-PORT. I left the "What would you like to compute?" section where it was, and moved "Select your pollutant" underneath it. The help text needs to be updated to match the interface changes, so I'll leave this issue open.

**Comment by joellenb** [comment]
Catherine,
We also need the Submit and the Save buttons moved (see first posting for this issue). The Save button needs to be in the lower left corner and the Submit button needs to be in the lower right corner.

**Comment by joellenb** [comment]
Updated the on-line help text for the C-LINE analysis menu.
I'm reassigning this issue to Catherine to move the Submit and Save buttons.

**Comment by cseppan** [comment]
I moved the Save and Submit buttons in C-PORT and C-LINE.
