### ISSUE TITLE
CTOOLS_HOURLY segmentation fault

### ISSUE THREAD

**Issue by cseppan** [CEMPD/ctools#143]
CTOOLS_HOURLY.ifort.x ROAD ../1434393752.96/
 Source type is: ROAD
 Input directory is: ../1434393752.96/
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
CTOOLS_HOURLY.ifo  000000000040DDD4  read_moves_               113  road_read_moves.f90
CTOOLS_HOURLY.ifo  0000000000410757  compute_hourlyemi          90  road_compute_hourlyemissions.f90
CTOOLS_HOURLY.ifo  000000000040FBFF  road_                      51  road.f90
CTOOLS_HOURLY.ifo  0000000000406003  MAIN__                     31  ctools_main.f90
CTOOLS_HOURLY.ifo  000000000040330C  Unknown               Unknown  Unknown
libc.so.6          00000030A361ED5D  Unknown               Unknown  Unknown
CTOOLS_HOURLY.ifo  0000000000403219  Unknown               Unknown  Unknown

**Comment by cseppan** [comment]
In case another data point helps - different inputs, same error:

CTOOLS_HOURLY.ifort.x ROAD ../1434394225.0/
 Source type is: ROAD
 Input directory is: ../1434394225.0/
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
CTOOLS_HOURLY.ifo  000000000040DDD4  read_moves_               113  road_read_moves.f90
CTOOLS_HOURLY.ifo  0000000000410757  compute_hourlyemi          90  road_compute_hourlyemissions.f90
CTOOLS_HOURLY.ifo  000000000040FBFF  road_                      51  road.f90
CTOOLS_HOURLY.ifo  0000000000406003  MAIN__                     31  ctools_main.f90
CTOOLS_HOURLY.ifo  000000000040330C  Unknown               Unknown  Unknown
libc.so.6          00000030A361ED5D  Unknown               Unknown  Unknown
CTOOLS_HOURLY.ifo  0000000000403219  Unknown               Unknown  Unknown

**Comment by cseppan** [comment]
Found the problem. The first case uses the reference county 36103. The temperatures in the January file range from -30 to 95. The array temp28 in line_source_data.f90 starts at -20, so there's no matching bin for the data.

**Comment by cseppan** [comment]
Looking through the emission factors files, temperatures in reference county 04013 (Maricopa County, AZ) go up to 130 in July.

**Comment by cseppan** [comment]
And down to -40 in some counties.

**Comment by joellenb** [comment]
Well, I was at a conference there one July and it was > 110 degF each day. Here are the daily records for July. I do see over 120.

http://weather.azkiwis.net/wxnoaarecords.php?month=July



Jo Ellen

**Comment by cseppan** [comment]
Regardless of actual temperatures, the emission factors files have data ranging from -45 to 130 so CTOOLS_HOURLY has to be able to handle that data.

**Comment by arunacs** [comment]
Looks like this a code update issue for Michelle.

On Jun 15, 2015, at 5:49 PM, Catherine Seppanen <notifications@github.com<mailto:notifications@github.com>> wrote:


Regardless of actual temperatures, the emission factors files have data ranging from -45 to 130 so CTOOLS_HOURLY has to be able to handle that data.

**Comment by michellegrace** [comment]
Thanks for the detective work! Iput some time in to make these variables more global, so I can update this in one file instead of 4. I ran these two cases and I did not get the segmentation fault. This update will be migrated when I make another dated version later today.
