### ISSUE TITLE
CTOOLS_ANNUAL segmentation fault

### ISSUE THREAD

**Issue by cseppan** [CEMPD/ctools#144]
Just tested with the latest (CTOOLS_06_16_2015) build.

% CTOOLS_ANNUAL.ifort.x ROAD ../1434462558.53/
 Source type is: ROAD
 Input directory is: ../1434462558.53/
Read inputs runtime =      0.034 seconds.
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
CTOOLS_ANNUAL.ifo  0000000000410877  aa_road_                  126  aa_road.f90
CTOOLS_ANNUAL.ifo  0000000000405FF4  MAIN__                     31  aa_ctools_main.f90
CTOOLS_ANNUAL.ifo  000000000040330C  Unknown               Unknown  Unknown
libc.so.6          00000030A361ED5D  Unknown               Unknown  Unknown
CTOOLS_ANNUAL.ifo  0000000000403219  Unknown               Unknown  Unknown

**Comment by cseppan** [comment]
Problem is due to memory limits. Lots o' receptors * lots o' roads = BOOM!

Review receptor generation
- use zoom level to set line transect spacing
- use zoom level to set offset spacing
- look at removing duplicate receptors (within some radius - based on zoom?)
- what receptor resolution is useful in actually interpolating results?

**Comment by cseppan** [comment]
Michelle will add checks for allocation errors. Catherine will look at making web app detect executable problems and show errors to users.

**Comment by michellegrace** [comment]
Nothing actually.... the standard Charleston domain I had been using did not have a memory problem. But Catherine had zoomed out and so there were more roads and thus more receptors increasing the memory needed to compute, so it hit this memory limit and barffed! 

We also played around with using the same domain and adjusting the spacing of receptors around roadways and this decreased the number of receptors and it ran successfully. We will work on some quick fixes to decrease the number of receptors in an intelligent way (see Catherine's comment above). After release we can go through some more rigorous steps to intelligently decrease the number of receptors needed, so we don't have this memory problem.

I updated my fortran code to "throw" errors when it hits a memory limit.

**Comment by cseppan** [comment]
Documenting some numbers regarding on-screen pixels vs. real world sizes:

zoom level | scale | pixels | resolution
------------ | ------------- | ------------- | -------------
11 (min) | 5 km | 76 px | 66 m/px
12 (default) | 2 km | 61 px | 33 m/px
13 | 1 km | 61 px | 17 m/px
14 | 500 m | 61 px | 8 m/px
15 (max) | 200 m | 49 px | 4 m/px

The concentrations overlay image is 1600 px along the maximum dimension (height or width), regardless of viewport or zoom level, so the m/px in the image can vary.

**Comment by cseppan** [comment]
I updated the receptor spacing along line segments to be based on zoom level:

zoom level < 12: spacing = 1000 m
else if zoom level <= 14: spacing = 500 m
otherwise: spacing = 200 m

**Comment by cseppan** [comment]
I confirmed that the updated CTOOLS_ANNUAL executable exits if it can't allocate enough memory, preventing a later segmentation fault. Note that this only works on treehug since the Fortran program can get info from the underlying system about actual memory available. On killdevil, it appears that allocations succeed, but the process will be killed when it attempts to use more memory than requested when the job was submitted. This will be something to address once we switch to sending jobs off to killdevil for processing.

I also updated the web app so that errors when running the Fortran programs are detected immediately rather than having to wait for the full 20 minute timeout. The same generic error message is shown to the user:

    A server error occurred; please check your inputs before submitting again.

There's several layers between running the Fortran programs and informing the user, so trying to give customized error messages would be problematic at this point.

**Comment by cseppan** [comment]
Michelle, can you add an allocation status check to road_read_fleetmix.f90? I'm seeing segmentation faults further along in the process and want to confirm that it's due to lack of memory.

 Source type is: ROAD
 Input directory is: 
 /nas01/depts/ie/cempd/EPA-RARE/ctools/street2/1435044488.71/
Read inputs runtime =      0.037 seconds.
Dispersion runtime =    606.090 seconds.
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
CTOOLS_ANNUAL.ifo  000000000040F2C1  read_fleetmix_             30  road_read_fleetmix.f90
CTOOLS_ANNUAL.ifo  0000000000412002  aa_road_                  235  aa_road.f90
CTOOLS_ANNUAL.ifo  0000000000406144  MAIN__                     31  aa_ctools_main.f90
CTOOLS_ANNUAL.ifo  000000000040330C  Unknown               Unknown  Unknown
libc.so.6          0000003EDE21ED5D  Unknown               Unknown  Unknown
CTOOLS_ANNUAL.ifo  0000000000403219  Unknown               Unknown  Unknown

**Comment by michellegrace** [comment]
Done in latest release version data 06/25/15. Leaving the issue open (see previous comments).

**Comment by cseppan** [comment]
Updated web app code to just use grid of receptors for annual runs - no receptors added along line sources. This limits the number of receptors to 2500 regardless of the number of sources. Hourly analysis still adds additional line segment receptors with adaptive spacing based on zoom level.

All tests of annual analyses are now running successfully.
