### ISSUE TITLE
comparison plot scale seems to be off

### ISSUE THREAD

**Issue by cseppan** [CEMPD/ctools#146]
Look at Brian's testing. Absolute max difference ~ 145000. Log 10 ~ 5. CTOOLS difference plot has max legend of 10^3.

**Comment by briannaess** [comment]
![canav_summer_conv_incby25percdif_with_values](https://cloud.githubusercontent.com/assets/10236069/8237100/d8da92da-15ba-11e5-8f43-a9ead5251283.PNG)
![canav_summer_conv_incby25perc_diffplot](https://cloud.githubusercontent.com/assets/10236069/8237113/f7ef7b0e-15ba-11e5-8f56-b2b75f1e117e.PNG)

**Comment by cseppan** [comment]
In the spreadsheet, ConcDif is the percent difference between ConcBase and concScen. 0.007125 vs. 1034.868476 is a 145,234% increase. log10(145234.444085) = 5.16207.

However, the C-PORT image is showing the absolute concentration difference. 0.007125 vs. 1034.868476 is a difference of 1,034.861351. log10(1034.861351) = 3.01488.

C-PORT can generate a plot showing the percent difference, by setting the Mode to Relative (%) instead of Relative. In that case, the legend would be labeled "PM2.5 concentration difference (%)" instead of "PM2.5 concentration difference (ug/m^3)".
