### ISSUE TITLE
Difficulty comparing scenarios in C-PORT public version

### ISSUE THREAD

**Issue by kdtalgo** [CEMPD/ctools#149]
I'm getting the following error message when running the Compare Scenarios feature in C-PORT for certain ports:

"A server error occurred; please check your inputs before submitting again."

I simply switched the stability option from its default of Stable to Convective with all source types turned on and tried running the comparison for several ports. It succeeds for certain ports, and fails for others. I had success in Morehead City and Port Canaveral, but it failed in Charleston, Savannah, Biloxi, and Tampa. The error appears immediately when clicking the button for Charleston, Savannah, and Tampa, but it takes a few seconds for it to happen for Biloxi. The ports where it is succeeding are smaller ports. I tried playing with some other options in ports where it is failing (e.g. doubling NOx emissions for area sources) but this does not change anything. It always fails for these ports.

I suspect it is a CPU issue on the public server. There are not enough resources to run two scenarios simultaneously for these larger ports where there are lots of sources. I did not have this problem on Treehug.

**Comment by cseppan** [comment]
Turns out the web server was unhappy with the amount of data the browser was trying to submit (all the sources for two scenarios). I updated the production server to match treehug's setting, and successfully compared two scenarios in Charleston.
