### ISSUE TITLE
White box in lower right-hand corner?

### ISSUE THREAD

**Issue by michellegrace** [CEMPD/ctools#15]
What is this? To the user it looks like it should be something, but nothing happens when you click on it. Here is a screen shot (I overlaid a big red arrow to show you the box I am talking about):
![screen shot 2014-12-12 at 8 11 29 am](https://cloud.githubusercontent.com/assets/10077162/5412051/c25f7412-81d6-11e4-966a-79934bfb2a05.png)

When you compute concentrations the box goes away, here is a screen shot of this:
![screen shot 2014-12-12 at 8 14 18 am](https://cloud.githubusercontent.com/assets/10077162/5412069/f65a0250-81d6-11e4-95ba-43fa4ee77305.png)

Is the white box a blank color bar? If so, this should be invisible to the user until after concentrations are computed. 

Also note, that the displayed concentrations in the above screen shot are still messed up, i.e. "choppy" or not matching the smooth pattern we would expect from dispersion model results. (this has been documented in issue #3 (interpolation craziness).

Comment based on current tree hug version of C-LINE (12/12/14 ~8:00am).

**Comment by cseppan** [comment]
I updated the legend box to not display until the analysis outputs are available.
