### ISSUE TITLE
Source types not showing up after changing ports

### ISSUE THREAD

**Issue by kdtalgo** [CEMPD/ctools#150]
If the checkbox for a certain source type is not checked when switching ports, that source type will NOT be loaded and you cannot calculate concentrations if you try to run with that source type. 
If you don't recheck the box before selecting the new port, the source type is not loaded.

For example, I did a test in Charleston where I ran for all source types except roadways. I then moved to Savannah, rechecked the roadway box, and hit submit. It appears to run, but no contours are displayed upon completion. You can see that the roadways are not loaded on the map before hitting run.

Other selections (such as stability options) are not changed back to their defaults either when switching to a new port.

It took me a while to figure out what was going on, so I imagine this would be a major source of confusion for the average user. We need to have C-PORT force all options back to their defaults and automatically re-check all source type boxes when a user selects a new port from the pulldown tab.

**Comment by cseppan** [comment]
I updated the port selection (either using the pull-down menu or clicking a location marker) so that all the source types get enabled when changing cities. I put the update in place on both treehug and ctools production.

**Comment by cseppan** [comment]
Oops, just realized the change has unintended effects in C-LINE as well. I've pulled it off of ctools production.

**Comment by kdtalgo** [comment]
Can we also force the pulldown tabs (e.g. stability settings) to their default values when switching ports as well?

**Comment by cseppan** [comment]
Now, all of the analysis settings (stability, seasons, source types, etc.) will reset when you switch locations. Note that pollutant and analysis mode (What would you like to compute?) are not saved in the scenario, but they will now get reset.
