### ISSUE TITLE
Compare scenarios does not work in C-PORT

### ISSUE THREAD

**Issue by michellegrace** [CEMPD/ctools#171]
This is Brian's finding... discuss with him further, but here is what I know...

Brian was trying to do a comparison between a "BASE" case and adding a "New_Terminal". He keeps getting a server error on treehug, here are the output logs: 

[ /nas/depts/003/cep-emc/proj/EPA-CTOOLS/web/treehug/street2/output ] $ ldate | tail
-rw-r--r--   1 cseppan cep-emc  418544 Aug  6 10:40 BusyI_40_143887201812.tar.gz
-rw-r--r--   1 cseppan cep-emc  351611 Aug  6 10:41 BusyI_40_vs_Baseline_143887207034.tar.gz
-rw-r--r--   1 cseppan cep-emc  301055 Aug  6 10:46 BusyI_40_143887213938.tar.gz
-rw-r--r--   1 cseppan cep-emc 1419958 Aug  6 10:52 BASE_14388726786.tar.gz
-rw-r--r--   1 cseppan cep-emc 1424842 Aug  6 10:58 New_Terminal_143887300467.tar.gz
-rw-r--r--   1 cseppan cep-emc 1419968 Aug  6 11:20 BASE_143887432243.tar.gz
drwxr-xr-x   2 cseppan cep-emc   28672 Aug  6 11:28 ./
-rw-r--r--   1 cseppan cep-emc 1370578 Aug  6 11:28 _BASE_143887484411.tar.gz
drwxr-xr-x 527 cseppan cep-emc   45056 Aug  6 11:32 ../

He was able to do a comparison between a "Baseline" and "BuzyI_40" on C-LINE, and this ran successfully (as seen in the logs). But when he ran C-PORT it appears that the comparison of "BASE" and "New_Terminal" was never created. He tried this multiple times and created a second base scenario, "_BASE", but still the same problem.

**Comment by cseppan** [comment]
Since the new terminal scenario has additional line sources, this changes the number of receptors. The comparison code doesn't handle this difference yet, so the error is due to the results arrays being different sizes.

**Comment by cseppan** [comment]
The current development versions of C-LINE and C-PORT now handle this situation when comparing scenarios.
