### ISSUE TITLE
C-LINE: Reset map center and zoom level

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#173]
I selected a location, changed the zoom level, and panned to a different map extent. When I clicked on the "Reset map center and zoom level" text, C-LINE appeared to turn off the line sources and then turn them back on (colored pink). But neither the zoom level nor the map extent was changed.

I expected the map center and zoom level would be changed back to the original one shown when I selected the location. What is supposed to happen?

**Comment by cseppan** [comment]
The map center and zoom level isn't set until you enter edit mode, either by making changes to a source or manually toggling edit mode. It sounds like you were moving around the map before entering edit mode, not after, and so resetting didn't need to do anything.
