### ISSUE TITLE
C-PORT annual average broken

### ISSUE THREAD

**Issue by kdtalgo** [CEMPD/ctools#175]
Something is wrong with the annual averaging in C-PORT. The magnitudes of the annual concentrations are way too high relative to the hourly values. For example, using the Charleston defaults, we get >200ppb NOX nearly everywhere in the domain, leading to solid yellow contouring everywhere. The problem is coming from the ships in transit. I tested multiple ports and it is happening everywhere.

**Comment by michellegrace** [comment]
Kevin,
Thanks! .. I think I found an extra factor of 10^6 in an inner loop for SIT sources. I missed this extra factor when I moved the conversion of grams to micrograms into an outer loop. I updated the "CURRENT" pointer, so this should be fixed now on treehug.

I checked this for NOx with my scripts to get annual averages...
[ /nas/depts/003/cep-emc/web/ctools/treehug/street2 ] $ head CLINE/charleston/results_CTOOLS_ANNUAL_SIT_Output.csv 
 RecID, xLCC, yLCC, NOx(ppb)
 1,  0.159937E+07, -0.651424E+06,  0.552244E+01
 2,  0.158771E+07, -0.640477E+06,  0.133454E+00
 3,  0.158731E+07, -0.643708E+06,  0.453096E-03
 4,  0.158745E+07, -0.643711E+06,  0.485894E-03
 5,  0.158026E+07, -0.655088E+06,  0.440786E-02
 6,  0.159340E+07, -0.639835E+06,  0.429583E-01
 7,  0.159991E+07, -0.657100E+06,  0.532680E-02
 8,  0.158352E+07, -0.633984E+06,  0.331657E-03
 9,  0.158476E+07, -0.641027E+06,  0.403498E-03
[ /nas/depts/003/cep-emc/web/ctools/treehug/street2 ] $ head CLINE/charleston/results_CTOOLS_ANNUAL_ROAD_Output.csv  
 RecID, xLCC, yLCC, NOx(ppb)
 1,  0.159937E+07, -0.651424E+06,  0.202649E-02
 2,  0.158771E+07, -0.640477E+06,  0.143579E+00
 3,  0.158731E+07, -0.643708E+06,  0.140018E+03
 4,  0.158745E+07, -0.643711E+06,  0.734654E+02
 5,  0.158026E+07, -0.655088E+06,  0.457042E+01
 6,  0.159340E+07, -0.639835E+06,  0.360662E+02
 7,  0.159991E+07, -0.657100E+06,  0.000000E+00
 8,  0.158352E+07, -0.633984E+06,  0.566610E-01
 9,  0.158476E+07, -0.641027E+06,  0.556751E+02
[ /nas/depts/003/cep-emc/web/ctools/treehug/street2 ] $ head CLINE/charleston/results_CTOOLS_ANNUAL_RAIL_Output.csv  
 RecID, xLCC, yLCC, NOx(ppb)
 1,  0.159937E+07, -0.651424E+06,  0.000000E+00
 2,  0.158771E+07, -0.640477E+06,  0.118159E-01
 3,  0.158731E+07, -0.643708E+06,  0.176004E+01
 4,  0.158745E+07, -0.643711E+06,  0.563284E+01
 5,  0.158026E+07, -0.655088E+06,  0.000000E+00
 6,  0.159340E+07, -0.639835E+06,  0.000000E+00
 7,  0.159991E+07, -0.657100E+06,  0.000000E+00
 8,  0.158352E+07, -0.633984E+06,  0.171253E+01
 9,  0.158476E+07, -0.641027E+06,  0.349460E-01
[ /nas/depts/003/cep-emc/web/ctools/treehug/street2 ] $ head CLINE/charleston/results_CTOOLS_ANNUAL_POINT_Output.csv 
 RecID, xLCC, yLCC, NOx(ppb)
 1,  0.159937E+07, -0.651424E+06,  0.189043E-01
 2,  0.158771E+07, -0.640477E+06,  0.121201E-01
 3,  0.158731E+07, -0.643708E+06,  0.630887E-02
 4,  0.158745E+07, -0.643711E+06,  0.653195E-02
 5,  0.158026E+07, -0.655088E+06,  0.210713E-02
 6,  0.159340E+07, -0.639835E+06,  0.729981E+00
 7,  0.159991E+07, -0.657100E+06,  0.159211E-02
 8,  0.158352E+07, -0.633984E+06,  0.206642E-01
 9,  0.158476E+07, -0.641027E+06,  0.983690E-02

This seems much more reasonable, now there are higher concentrations for other source types than SIT... however, when I run this on treehug it only seems to show the SIT:

![screen shot 2015-09-22 at 11 16 35 am](https://cloud.githubusercontent.com/assets/10077162/10022549/7766d5c0-611b-11e5-875e-3bde6f3a497a.png)

Catherine, can you check that the interpolation to make the image is really showing the TOTAL?

**Comment by kdtalgo** [comment]
Hmmm I just did an annual test in Seattle and it shows contributions from all source types.

**Comment by michellegrace** [comment]
I believe this has been fixed. I am going to close this issue.
