### ISSUE TITLE
Roads missing from annual average

### ISSUE THREAD

**Issue by kdtalgo** [CEMPD/ctools#177]
Roads are not being included in the total for annual averages.

**Comment by kdtalgo** [comment]
Annual average and cancer risk modes are also failing every time in C-LINE. I'm guessing these 2 issues are related.

**Comment by cseppan** [comment]
The CTOOLS_09_22_2015 version of CTOOLS_ANNUAL.ifort.x is failing with a segmentation fault on treehug. It's due to the limited stack size on the machine (same as the login nodes for killdevil). I compiled an updated executable that allocates the road dispersion array onto the heap instead of the stack.

```
> git diff aa_road.f90 
diff --git a/aa_road.f90 b/aa_road.f90
index b6c812e..1aba644 100644
--- a/aa_road.f90
+++ b/aa_road.f90
@@ -39,7 +39,7 @@ subroutine aa_road(Conc)
 
 ! Local variables:
       Real(kind=double)  :: Concd    !  Dummy concentration at receptor
-      Real(kind=double), dimension(Number_Receptors,100,Number_Sources) :: Disp
+      Real(kind=double), Allocatable :: Disp(:,:,:)
       Integer            :: index, isource, AllocateStatus,imet
       Integer             :: v, jm
       Integer              :: repS, repC, new_repS, new_repC
@@ -50,6 +50,13 @@ subroutine aa_road(Conc)
      
 Call cpu_time(start)
 
+ Allocate(Disp(Number_Receptors,100,Number_Sources),Stat=AllocateStatus)
+    if(AllocateStatus .NE. 0) then
+        print *,"Disp allocation error"
+        stop
+    end if
+ Disp(:,:,:) = 0.0
+
  call read_taf
  call read_mapping
  call road_height_width 
```

**Comment by kdtalgo** [comment]
Thanks! Roads are showing up now.

**Comment by michellegrace** [comment]
Thanks Catherine. I did not run into this in my testing, but maybe treehug is slightly different. I will update release version on nas/003/ and re-run my scripts.

-Michelle

From: kdtalgo
Reply-To: CEMPD/ctools
Date: Tuesday, September 22, 2015 at 4:43 PM
To: CEMPD/ctools
Subject: Re: [ctools] Roads missing from annual average (#177)


Thanks! Roads are showing up now.

**Comment by cseppan** [comment]
You'd only run into the seg fault if you try to run the executable directly (i.e. on a login node), not through killdevil's queues. We're not yet using the queuing system for runs submitted through the web applications.

**Comment by michellegrace** [comment]
Ok… makes sense-ish.

I just updates my files, the release version, and queued up the example runs that I usually include with the release versions.

-Michelle

From: Catherine Seppanen
Reply-To: CEMPD/ctools
Date: Tuesday, September 22, 2015 at 5:04 PM
To: CEMPD/ctools
Cc: "Snyder, Michelle G"
Subject: Re: [ctools] Roads missing from annual average (#177)


You'd only run into the seg fault if you try to run the executable directly (i.e. on a login node), not through killdevil's queues. We're not yet using the queuing system for runs submitted through the web applications.
