### ISSUE TITLE
Expected run-times on Perform analysis screen

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#178]
My understanding is that C-LINE and C-PORT now perform the analyses in the background so the user can perform other tasks instead of waiting for the analysis to complete. If that is the case, then can we remove the expected run-times on the Perform analysis screen?

![c-line_performanalysis_times_09222015](https://cloud.githubusercontent.com/assets/10145737/10028958/6c08a36c-613d-11e5-9e4c-3854b98473a4.PNG)

**Comment by cseppan** [comment]
Yeah, I meant to remove those from C-LINE. I just pushed the updated version to treehug.
