### ISSUE TITLE
C-LINE: How to determine why a scenario failed

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#179]
I created a scenario with 1 added road complete with data. Scenario was named and saved. When I went to the Load a previous scenario I looked on the Run tab. My scenario is listed but the status is "failed".

![failedscenario_09222015](https://cloud.githubusercontent.com/assets/10145737/10031187/cb5edcd0-6149-11e5-8eca-5011f8ebdfe0.PNG)

How can I find out why the scenario failed? I thought that perhaps the simulation had not completed, so I waited and then clicked the Refresh button (a few times). The Status remained "failed".

**Comment by cseppan** [comment]
If the Python code throws an exception, the catch block sets the status to Failed. On treehug, the stack trace should get printed into the run log in /nas/depts/003/cep-emc/web/ctools/treehug/logs/.
