### ISSUE TITLE
Adding a source in C-LINE

### ISSUE THREAD

**Issue by kdtalgo** [CEMPD/ctools#180]
The "add a source" function isn't working in C-LINE. You're physically able to add a new road link, and the input parameters (e.g. AADT) appear to be correct, but the new link does not produce any concentrations.

I'm able to delete existing road links and produce differences. It's just adding links that gives me a problem.

It's working fine in C-PORT...

**Comment by cseppan** [comment]
I fixed a problem in processing new road sources. Should be working on treehug now.
