### ISSUE TITLE
After working in C-PORT for awhile could not get the tiles to activate

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#181]
During testing I created, saved, ran, and viewed result for several scenarios. All of them were related to Charleston, SC. C-PORT got to where it would not allow me to get into edit mode.

I went to the Select your location tile and selected Charleston, SC again. It appeared as thought I got a fresh map, but sources were missing on it. The icons were grayed out.
![c-port_newscenarionosources_10262015](https://cloud.githubusercontent.com/assets/10145737/10741330/91d66e6e-7bfd-11e5-8c02-91489e9ab5db.PNG)

**Comment by joellenb** [comment]
Tried loading a different port that I had not used in this session. Loaded Baltimore, MD port and appeared to load correctly (showed sources and tiles as expected). Then, loaded Charleston, SC port again and sources/tiles loaded as expected.

**Comment by cseppan** [comment]
Fixed by commit 287087ad7f480edc5a2333b30c95e0ee44dc8206
