### ISSUE TITLE
Selected road disappears when editing

### ISSUE THREAD

**Issue by briannaess** [CEMPD/ctools#182]
If you view the tutorial around the 7:20 minute mark, you'll see that when I edit the new road, the selected road (red color) disappears from the map

**Comment by arunacs** [comment]
This is the final version of the tutorial that we have, and which will be made available with the CTOOLS v2 release. 

https://www.youtube.com/watch?v=MhvLldObKhg&feature=youtu.be

**Comment by cseppan** [comment]
Fixed in commit 8cdd95815f292e424ef48cf375536ae49bb18eea.
