### ISSUE TITLE
Issue with initializing C-PORT for a new scenario

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#186]
I have been observing some errors that appear to originate with an initialization issue. Specifically, after Perform analysis has been executed the tiles and data are not reset  under any of the following actions:
* Visualization options/clear overlay
* Editing data and Save as a New Scenario
* Load a Scenario
* Select your location and select the same port
* Changing the extent of the map 

In order to completely reset an analysis, I had to perform a Select your location, select a different port, wait for the screen to show all sources for that port, and then perform a Select your location and select the port with which I had been working.

See attachment for details.
[testing_notes_InitializationIssue_102015.docx](https://github.com/CEMPD/ctools/files/25625/testing_notes_InitializationIssue_102015.docx)

**Comment by cseppan** [comment]
Fixed by commit 287087ad7f480edc5a2333b30c95e0ee44dc8206. Separate issue for discussion of desired behavior in #185.
