### ISSUE TITLE
C-PORT: No results shown on map when emissions are nonzero

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#187]
Test case was Charleston, SC; ship-in-transit sources; annual; acrolein

![c-port_chars_sitannualacrolein](https://cloud.githubusercontent.com/assets/10145737/10892684/e66f46ce-8172-11e5-8fe9-8d4ee36be903.PNG)

The acrolein emissions for the Ship-in-transit sources are nonzero. When this map was shown in a meeting the group suggested that the legend was empty and no thematic colors were apparent on the map, meaning that the concentration values were less than 1E-6. The above figure shows the results of using the prob, where the concentrations are shown to be 0.000 ug/m3 even directly on a ship-in-transit line source.

Why are concentrations 0.000 for nonzero sources?

**Comment by cseppan** [comment]
Tested on Nov. 12, 2015. Seems to be resolved.

**Comment by joellenb** [comment]
Retested 11/23/2015. Issue still exists. The inspect mode shows all concentrations probed along shipping lanes as 0.000 when the ship-in-transit emissions were nonzero. 
If the calculated concentrations are below a cutoff value, then the probed values should show
< [cutoff value] (e.g., for cutoff value = 1E-6, C-PORT's inspect mode would show < 1E-6).

**Comment by cseppan** [comment]
I need more details of exactly what you're testing. Here's the specific steps I took to produce the screenshot below.
Load http://treehug.its.unc.edu/ctools/cport/
Select location Charleston, SC.
In the Perform analysis window, select Annual average concentrations and set the pollutant to Acrolein.
Uncheck Area, Point, Rail, and Road sources.
Click Submit.
![screen shot 2015-11-30 at 12 56 36 pm](https://cloud.githubusercontent.com/assets/7329179/11479830/0084c426-9762-11e5-949d-c62c520323cf.png)

**Comment by joellenb** [comment]
I apologize. I had a typographical error when copying from my testing document into the GitHub issue. The test was for hourly default conditions. I just ran it again and got the same result.

![charlestonsit_defhrly_acrolein](https://cloud.githubusercontent.com/assets/10145737/11481211/0cdeeb90-976a-11e5-9441-9d915a896f06.PNG)

This shows the same results as the image that I showed in the meeting. I questioned how the hourly statistics could be 0 for all conditions when the emissions values and the annual statistics show nonzero. Also, I questioned why no results are shown on the map for nonzero emissions. The group suggested that the values were below a cutoff value of 1E-6. However, after running the scenario again the concentrations show as 0.000 not as a cutoff value, but other maps show <1E-6 when the concentration value is less than the cutoff value of 1E-6.

**Comment by cseppan** [comment]
With the default hourly settings (Neutral stability, Winter season, Seasonal Average wind direction), the dispersion model outputs the concentrations as 0 for all receptors in the domain. So, there's nothing to display on the concentration overlay. I'm not sure what other behavior you're expecting.

**Comment by joellenb** [comment]
As per request tested Charleston, ships-in-transit, default hourly conditions for formaldehyde and for benzene. Here are the results for formaldehyde (same as for acrolein):
![charleston_defhrly_sit_form](https://cloud.githubusercontent.com/assets/10145737/11578138/b8a387a0-99f0-11e5-8ce5-107326bba03e.PNG)
 Benzene results are different. I am unable to find where there is a nonzero concentration, but a legend was filled in. 
![charleston_defhrly_sit_benz](https://cloud.githubusercontent.com/assets/10145737/11578149/dcc346c0-99f0-11e5-92a8-c2b21d6b90d7.PNG)

**Comment by michellegrace** [comment]
I tracked this down to a conversion factor error in the SIT hourly code. I will wait to close the issue till Jo Ellen confirms it is fixed.

**Comment by joellenb** [comment]
Retested C-PORT for Charleston, default Hourly, Ships-in-Transit only, acrolein. Test passed. Note that concentrations are small but are not less then the 1E-6 cutoff value for display.

![c-port_charleston_sit_defhrly_12072015](https://cloud.githubusercontent.com/assets/10145737/11634878/28462d72-9ce1-11e5-8bab-0210161ba9bc.PNG)
