### ISSUE TITLE
C-LINE: changing zoom level does not refresh road segments

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#195]
I did "Select your location", put in St. Louis, MO, and submitted that. The map zoomed and centered on St. Louis. Road segments showed up in pink.

I zoomed out. No additional road segments were displayed in pink.
![c-line_rdsnotrefreshedzoomout_stl_12172015](https://cloud.githubusercontent.com/assets/10145737/11883776/3b688350-a4e3-11e5-9285-f7dcf7f15c82.PNG)
When I zoomed out another level all the pink lines disappeared and even the tile for the roads could no longer be selected.
![c-line_rdsdisappearzoomout_stl_12172015](https://cloud.githubusercontent.com/assets/10145737/11883821/7f83fa24-a4e3-11e5-918d-de027caad213.PNG)

**Comment by cseppan** [comment]
There was a database error earlier that might have caused the first issue. Zooming out two steps from the default zoom level takes you out of source display range.
