### ISSUE TITLE
C-LINE: error message "There was a problem loading the sites"

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#196]
When in a rural area without any monitoring sites, I turned on the air quality monitors overlay. I got a popup box "There was a problem loading the sites.".
![c-line_problemloadingsiteserrormsg_12172015](https://cloud.githubusercontent.com/assets/10145737/11884318/069983fa-a4e7-11e5-8e29-c29bce47574a.PNG)
I got the same error message where there should have been sites in Greater St. Louis. This occurred even when site locations should have been within the geographic region included on the screen. Using Turn off and Turn on buttons just repeated the error. Making the air quality monitors box go away, bringing it back, and clicking the Turn on button sometimes (not always) made the sites display. Note on following screen capture where the extent of the roads is smaller than the extent of the window (see prior Issue posted today) while the monitor sites are located both within and outside the pink line segments.
![c-line_sitesloadedonpartialroadnetwork_12172015](https://cloud.githubusercontent.com/assets/10145737/11884418/bc24a18c-a4e7-11e5-971d-de9253c05af5.PNG)

**Comment by cseppan** [comment]
I restarted the web application to clear up a database error from earlier.
