### ISSUE TITLE
C-LINE: line segments above/below tiles

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#197]
The line segments appear underneath "active" tiles and above "inactive" (grayed out) tiles. Is this by design or an inconsistency to be fixed?
![c-line_roads_abovebelowtiles_12212015](https://cloud.githubusercontent.com/assets/10145737/11943446/f6a83838-a80b-11e5-8d62-96fc4c1334f4.PNG)

**Comment by cseppan** [comment]
The line segments are always behind the main menu buttons. The lines are more visible behind the inactive buttons because the disabled buttons only have an opacity of 40% (i.e. the buttons are transparent).
