### ISSUE TITLE
C-PORT Firefox issue?

### ISSUE THREAD

**Issue by michellegrace** [CEMPD/ctools#23]
Here is a screen shot...
![screen shot 2014-12-16 at 1 19 38 pm](https://cloud.githubusercontent.com/assets/10077162/5459149/5dd2e99a-8526-11e4-9d20-d691e14faf5e.png)

I decided to test using firefox on my mac, The menu bars are all displayed and I have refreshed multiple times and nothing happens to display the typical google earth map, like I have in safari. 

Jo Ellen mentioned that you told her to not use firefox, does this mean we should warn the user of this?

**Comment by cseppan** [comment]
In Safari, the JavaScript error is

TypeError: undefined is not a function (evaluating 'window.onGoogleReady()')

It looks like Google Maps can sometimes call the callback before the ctools.js evaluation is done, and so the function onGoogleReady() isn't defined yet. I updated cport.html to load the Google Maps JavaScript last, after the other JavaScript libraries are loaded. This matches how cline.html is laid out, so hopefully this will take care of it.
