### ISSUE TITLE
Select your location should give fresh map

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#70]
The "Select your location" allows the user to put in a new geographic location by name and then press the Select button to go to that location. Any results from the prior analysis should be blanked, showing a clean map.
![raleigh_newlocationshouldblank_02062015](https://cloud.githubusercontent.com/assets/10145737/6084507/847d108c-adff-11e4-844c-f483a18380e5.PNG)

**Comment by cseppan** [comment]
When you select a location, the old results overlay, the legend, and download results link are now hidden.
