### ISSUE TITLE
AADT up/down arrows in view and modify roads window

### ISSUE THREAD

**Issue by michellegrace** [CEMPD/ctools#71]
In the view and modify roads window then the user presses the up/down arrows this changes the AADT by 0.1. This is a really really small change, and we should look at this in the future. This should increase or decrease the AADT by at least a multiple of 1, if not 5 or 10.

Here is a screen shot: 
![screen shot 2015-02-06 at 1 11 16 pm](https://cloud.githubusercontent.com/assets/10077162/6084782/f60f55c8-ae01-11e4-849a-45133aab7d8a.png)

I changed the first road link and it looks like nothing is changing, but then I realized when I tried ti for the 3rd and 4th link it did change the AADT by 0.1. It works, so lets leave it for now, but I think this should be changed to a different increment in the next version. (and the user can just type in a new value if they do not want to click a million times).

Tested on tree hug ~1:10pm 2/6/15.

**Comment by cseppan** [comment]
I updated the AADT input to use an increment of 1 instead of 0.1.
