### ISSUE TITLE
C-LINE (treehug) cannot proceed with different geographic area after getting timeout for annual average

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#91]
After getting the timeout error message (A server error occurred; please check your inputs before submitting again.) on an annual average calculation I entered a new domain by city/state. I then went to the Perform Analysis tile but the submit button was still in an error condition. I went to the View and Modify Roads tile and then back to the Perform Analysis tile but the submit button was in an error condition.

How can this error condition be cleared? It should be cleared automatically, but if it isn't then how can the user clear it without closing out the browser window and opening a new one?

**Comment by nathan-rice** [comment]
The button is still clickable when the alert icon is present.

I've set the error alert icon to be cleared when the user selects a new city.
