### ISSUE TITLE
Need a STOP button on the Perform Analysis tile

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#92]
A STOP button needs to be added to the Perform Analysis tile. The function of this button is to cause the current analysis to stop and then to display a message to the user that the analysis was stopped successfully. Internally data structures associated with the analysis should be destroyed/deleted/purged/zeroed-out as appropriate.
Note that a restart capability is not planned.

**Comment by nathan-rice** [comment]
This just isn't feasible.  I could put a stop button on the page, but it wouldn't actually do anything other than change the spinning cursor back to "submit".

**Comment by michellegrace** [comment]
We need to find a work around for this. There needs to be a way to stop a calculation without completely reloading. (btw, if someone does this reloading after hitting submit, I would imagine it is still computing in the background and just doesn't ever send the result, correct?)

**Comment by nathan-rice** [comment]
Like I said, I can stop the button from spinning, that's it.  The computation will still take place on the server, and furthermore because of the way callbacks work, when the server is done with the computation the overlay and the legend will still pop up.

There is no workaround without completely re-engineering the product in a much more complex way.  That isn't going to happen.

**Comment by michellegrace** [comment]
Then we will leave this as an open issue, so someone can fix this in the future. 

Regardless, it should not be closed if it is not solved, this is a way to document known issues.

**Comment by nathan-rice** [comment]
Having a bunch of issues that are never going to be resolved makes this tool much less usable for me.  I'll add a "wishful thinking" tag, and filter my view so those don't show up.

**Comment by joellenb** [comment]
“future version” would be a better tag than “wishful thinking”.

Jo Ellen

**Comment by cseppan** [comment]
Sept. release will have async processing.
