### ISSUE TITLE
Pollutant name in csv files needs to be in quotation marks

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#93]
Pollutant names can contain commas, causing a problem with used as a column heading in csv files. To fix this problem the pollutant name needs to be surrounded by quotation marks prior to being saved to the csv file.

Ex. 1,3-BUTA should be saved as "1,3-BUTA"

**Comment by michellegrace** [comment]
I made this update in the write files for C-LINE and C-PORT. This will update on the next dispersion code update.

**Comment by michellegrace** [comment]
I had to change this again... brain says that GIS doesn't like "()" or spaces in the column headers. SO I made these "pollutant_units".
