### ISSUE TITLE
C-LINE (treehug & ctools): tool zooms in too far

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#97]
The scale to which a user can now zoom in is 50m. That should be larger.
![zoomtofarin_03032015](https://cloud.githubusercontent.com/assets/10145737/6473987/4caf1dbe-c1cb-11e4-80c8-e2b683361689.PNG)

This issue was confirmed today on both treehug and ctools by both Jo Ellen and Sarav.

**Comment by cseppan** [comment]
Updated code sets maximum zoom level to 15, down from 17. https://github.com/nathan-rice/ctools/pull/98
